/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check process health
         * @description Reports that the process is running. It does not check storage.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check service readiness
         * @description Reports whether the service can reach its database.
         */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the local service status */
        get: operations["getStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List configured sources */
        get: operations["listSources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List collection runs */
        get: operations["listRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read one run */
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the events explaining one run */
        get: operations["listRunEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the effective configuration
         * @description Returns each setting's effective value together with where it came
         *     from. Credentials are stored outside the configuration file and never
         *     appear here (ADR-005).
         */
        get: operations["getConfig"];
        /**
         * Replace the configuration file
         * @description Writes the whole configuration. Every known setting must be present:
         *     omitting one would silently reset it to its default.
         *
         *     `If-Match` is required and must carry the `ETag` from a preceding GET.
         *     A stale value means someone else changed the file first, and the write
         *     is refused rather than overwriting their edit (ADR-005, ADR-006).
         *
         *     The write lands in the file. A setting currently overridden by the
         *     environment keeps its overridden effective value, and the response
         *     reports its origin as `env`.
         */
        put: operations["replaceConfig"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @enum {string} */
            status: "ok" | "ready" | "unavailable";
        };
        Status: {
            /** @constant */
            status: "ok";
            version: string;
        };
        Error: {
            /**
             * @description A stable machine-readable code.
             * @enum {string}
             */
            error: "invalid_argument" | "not_found" | "method_not_allowed" | "precondition_required" | "precondition_failed" | "payload_too_large" | "internal";
            /** @description A human-readable explanation. */
            message: string;
            /** @description The parameter or setting the problem applies to. */
            field?: string;
        };
        Source: {
            /** Format: int64 */
            id: number;
            name: string;
            connector_kind: string;
            enabled: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        SourcePage: {
            items: components["schemas"]["Source"][];
            /**
             * Format: int64
             * @description Cursor for the next page, or null when the page is the last.
             */
            next_before: number | null;
        };
        Run: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            source_id: number;
            source_name: string;
            trigger: string;
            /** @enum {string} */
            status: "queued" | "running" | "succeeded" | "partial" | "failed" | "canceled" | "interrupted";
            /** Format: date-time */
            started_at: string;
            /** Format: date-time */
            finished_at: string | null;
            imported_count: number;
            duplicate_count: number;
            failed_count: number;
            attempt: number;
            last_error: string | null;
        };
        RunPage: {
            items: components["schemas"]["Run"][];
            /** Format: int64 */
            next_before: number | null;
        };
        RunEvent: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            run_id: number;
            /** @enum {string} */
            level: "info" | "warn" | "error";
            message: string;
            detail: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            occurred_at: string;
        };
        RunEventPage: {
            items: components["schemas"]["RunEvent"][];
            /** Format: int64 */
            next_before: number | null;
        };
        ConfigSetting: {
            /** @description Dotted path such as server.addr. */
            key: string;
            value: string;
            /**
             * @description Where the effective value came from.
             * @enum {string}
             */
            origin: "default" | "file" | "env" | "flag";
        };
        ConfigUpdate: {
            /** @description Every known setting. A missing one is an error, not a reset. */
            settings: {
                key: string;
                value: string;
            }[];
        };
        Config: {
            /** @description The configuration file consulted, whether or not it exists. */
            path: string;
            exists: boolean;
            settings: components["schemas"]["ConfigSetting"][];
        };
    };
    responses: {
        /** @description A parameter was not acceptable. */
        InvalidArgument: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The resource does not exist. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The request could not be completed. */
        Internal: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Page size. Values above the maximum are clamped to it. */
        Limit: number;
        /** @description Return only records with an id below this value. */
        Before: number;
        RunID: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The process is healthy. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The service is ready. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description The service cannot reach its database. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current service status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    listSources: {
        parameters: {
            query?: {
                /** @description Page size. Values above the maximum are clamped to it. */
                limit?: components["parameters"]["Limit"];
                /** @description Return only records with an id below this value. */
                before?: components["parameters"]["Before"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of sources, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourcePage"];
                };
            };
            400: components["responses"]["InvalidArgument"];
        };
    };
    listRuns: {
        parameters: {
            query?: {
                /** @description Page size. Values above the maximum are clamped to it. */
                limit?: components["parameters"]["Limit"];
                /** @description Return only records with an id below this value. */
                before?: components["parameters"]["Before"];
                /** @description Restrict the page to one source. */
                source_id?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of runs, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunPage"];
                };
            };
            400: components["responses"]["InvalidArgument"];
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The run. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            400: components["responses"]["InvalidArgument"];
            404: components["responses"]["NotFound"];
        };
    };
    listRunEvents: {
        parameters: {
            query?: {
                /** @description Page size. Values above the maximum are clamped to it. */
                limit?: components["parameters"]["Limit"];
                /** @description Return only records with an id below this value. */
                before?: components["parameters"]["Before"];
            };
            header?: never;
            path: {
                id: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of events, oldest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunEventPage"];
                };
            };
            400: components["responses"]["InvalidArgument"];
            404: components["responses"]["NotFound"];
        };
    };
    getConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The effective configuration. */
            200: {
                headers: {
                    /** @description Fingerprint of the configuration file, for use with If-Match. */
                    ETag: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Config"];
                };
            };
            500: components["responses"]["Internal"];
        };
    };
    replaceConfig: {
        parameters: {
            query?: never;
            header: {
                /** @description The ETag the edit was based on. */
                "If-Match": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigUpdate"];
            };
        };
        responses: {
            /** @description The configuration was written. */
            200: {
                headers: {
                    /** @description Fingerprint of the newly written file. */
                    ETag: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Config"];
                };
            };
            400: components["responses"]["InvalidArgument"];
            /** @description The file changed since the ETag was issued. */
            412: {
                headers: {
                    /** @description The current fingerprint. */
                    ETag: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The request body is too large. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description If-Match was not supplied. */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["Internal"];
        };
    };
}
